# General settings
api_url: https://mdr.kaspersky.com/api/v1
client_id: 1f1f1f1f1f1fc144a4b9a3af6a6a6a6a6a
#ssl_cert: conf/mdr.pem  # relative path from main.py
token_dir: conf  # relative path from main.py
data_dir: data  # relative path from main.py

# Modules settings
token_updater:
    timeout: 590  # default 600

mdr_sync:
    modules:
        incident:
            enable: false
            timeout: 60  # default 60
            max_incidents_at_time: 10  # how many incidents can be synced at a time. This parameter prevents a flood scenario.
            download_attachments_size_limit: 1000000  # max file size in bytes
            exclude_author: John Connor  # usually it's you own username. It's needed to prevent pulling your own comments
            filter:  # please visit API documentation to fill this settings correctly. https://support.kaspersky.com/MDR/RestAPI/REST_API_doc.html#tag/Incidents/paths/~1v1~1{client_id}~1incidents~1list/post
                statuses:
                    - Open  # Closed, On hold, Open, Resolved
                priorities:
                    - LOW  # LOW, NORMAL, HIGH
                min_creation_time: 1655096127000  # miliseconds
        asset:
            enable: true
            timeout: 60  # default 10800
            output_format: json  # default json
            filter:  # please visit API documentation to fill this settings correctly. https://support.kaspersky.com/MDR/RestAPI/REST_API_doc.html#tag/Assets/paths/~1v1~1{client_id}~1assets~1list/post
                statuses:
                    - ABSENT 
                    - CRITICAL
                    - OFFLINE
                    - OK
                    - WARNING

kuma:
    api_url: https://192.168.1.1:7223
    api_token: aa11bb22cc33dd44ee55ff66  # Settings -> Users -> <user> -> Generate token. Assign role and add API access rights to manage incidents.
    api_version: v3  # v2.1 (default) or v3. API version depends on KUMA version.
    tenant_id: 12345678-abcd-ef12-ab23-1a2b3c4d5e6f  # Tenant ID
    #ssl_cert: false
    modules:
        incident:
            enable: true
            timeout: 60  # default 60
        asset:
            enable: true
            timeout: 60  # default 10800

thehive:
    api_url: http://127.0.0.1:9000 
    api_key: jB79oI4ywUY1jBae5CdDmp4oyeuq0Dha
    ssl_cert: /opt/mdr/conf/thehive.pem  # full path
    modules:
        incident:
            enable: false
            timeout: 60  # default 60

event_sender:
    destination_host: 192.168.0.1  # IP address or resolvable hostname
    destination_port: 515
    protocol: tcp  # tcp/udp
    format: LEEF  # LEEF, CEF, raw
    syslog_header: true  # true, false
    modules:
        incident:
            enable: true
            timeout: 60  # default 60
        asset:
            enable: false
            timeout: 10800  # default 10800

logging:
    log_dir: log
    log_level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL